image: mono:4.4.0.182

stages:
- build

build_job:
    stage: build
    script:
     - nuget restore
     - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Release" /p:Platform="Any CPU" TrollChat.sln