dist: trusty
sudo: false

language: csharp
solution: TrollChat.sln



dotnet: 1.0.3

global_env: ASPNETCORE_ENVIRONMENT=Staging

before_script:
  - dotnet restore

script:
  #- dotnet build **/project.json -c Release
  - dotnet build TrollChat.sln -c Release
  - dotnet test ./TrollChat.BusinessLogic.Tests -c Release --no-build
