dist: trusty
sudo: required

language: csharp
solution: TrollChat.sln

notifications:
  email:
    on_failure: change # default: always

addons:
    apt:
        packages:
          - libunwind8

mono: # none
  #- 3.8.0
  - 3.10.0
  - 3.12.0
  #- latest

dotnet: 1.1.2

global_env: DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
global_env: DOTNET_CLI_TELEMETRY_OPTOUT=1

env:
    global:
        # Replace framework with core when you want to build a .NET Core project, not a .NET Framework project.
        - "TRAVIS_MSBUILD_MODE=core"
        # If using travis-msbuild as submodule, replace the TRAVIS_MSBUILD path!
        - "TRAVIS_MSBUILD=."
        - "TRAVIS_MSBUILD_BIN=$TRAVIS_MSBUILD/bin"
        # Replace the following path with the path to a copy of the .NET Framework you're depending on, f.e. a pre-built copy of the Mono Framework API.
        - "TRAVIS_MSBUILD_FRAMEWORK=$TRAVIS_MSBUILD/lib-dotnet"
        - "PATH=$PATH:$TRAVIS_MSBUILD_BIN"

before_script:
  - nuget restore
  - nuget restore TrollChat.sln
  - dotnet restore
  - dotnet restore TrollChat.sln

script:
  - xbuild /p:Configuration=Debug TrollChat.sln
  - msbuild /version
  - msbuild TrollChat.sln
  - dotnet build TrollChat.sln
  - dotnet build ./TrollChat.DataAccess
  - dotnet build ./TrollChat.BusinessLogic
  - dotnet build ./TrollChat.BusinessLogic.Tests
  - dotnet test ./TrollChat.BusinessLogic.Tests --no-build
