dist: trusty
sudo: false

language: csharp
solution: TrollChat.sln

mono: # none
  #- 3.8.0
  - 3.10.0
  #- 3.12.0
  #- latest

dotnet: 1.0.4

global_env: ASPNETCORE_ENVIRONMENT=Staging
global_env: DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
global_env: DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  - nuget restore
  - nuget restore TrollChat.sln
  - nuget restore ./TrollChat.DataAccess
  - nuget restore ./TrollChat.BusinessLogic

  - dotnet restore

script:
  - dotnet build TrollChat.sln
  - dotnet build ./TrollChat.DataAccess
  - dotnet build ./TrollChat.BusinessLogic
  - dotnet build ./TrollChat.BusinessLogic.Tests
  - dotnet test ./TrollChat.BusinessLogic.Tests
