dist: trusty
sudo: false

language: csharp
solution: TrollChat.sln

mono: none
  #- 3.8.0
  #- 3.10.0
  #- 3.12.0
  #- latest

dotnet: 1.0.4

global_env: ASPNETCORE_ENVIRONMENT=Staging
global_env: DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
global_env: DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  - dotnet restore
  - dotnet restore TrollChat.sln
  - dotnet restore ./TrollChat.DataAccess
  - dotnet restore ./TrollChat.BusinessLogic
  - dotnet restore ./TrollChat.Web
  - dotnet restore ./TrollChat.BusinessLogic.Tests

script:
  - dotnet build TrollChat.sln
  - dotnet build ./TrollChat.DataAccess
  - dotnet build TrollChat.sln
  - dotnet build ./TrollChat.BusinessLogic
  - dotnet build TrollChat.sln
  - dotnet build ./TrollChat.Web
  - dotnet build TrollChat.sln
  - dotnet build ./TrollChat.BusinessLogic.Tests
  - dotnet build TrollChat.sln
  - dotnet test ./TrollChat.BusinessLogic.Tests -c Release # --no-build
