dist: trusty
sudo: required

language: csharp
solution: TrollChat.sln

notifications:
  email:
    on_failure: change # default: always

mono: # none
  #- 3.8.0
  - 3.10.0
  - 3.12.0
  #- latest

dotnet: 1.1.2

global_env: DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
global_env: DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  - nuget restore
  - nuget restore TrollChat.sln
  - dotnet restore
  - dotnet restore TrollChat.sln

script:
  - dotnet build TrollChat.sln
  - dotnet build ./TrollChat.DataAccess
  - dotnet build ./TrollChat.BusinessLogic
  - dotnet build ./TrollChat.BusinessLogic.Tests
  - dotnet test ./TrollChat.BusinessLogic.Tests --no-build
