dist: trusty
sudo: required

language: csharp
solution: TrollChat.sln

notifications:
  email:
    on_failure: change # default: always

mono:
  #- 3.8.0
  - 3.10.0
  - 3.12.0
  - latest
  #- none

# .NET Core SDK version
dotnet: 2.0.0

global_env: DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
global_env: DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  - nuget restore
  - dotnet restore

script:
  - dotnet build ./TrollChat.DataAccess
  - dotnet build ./TrollChat.BusinessLogic
  - dotnet build ./TrollChat.BusinessLogic.Tests
  #- dotnet build ./TrollChat.Web
  - dotnet test --no-build
  - dotnet test
  - dotnet test ./TrollChat.BusinessLogic.Tests #--no-build
