dist: trusty
sudo: false

language: csharp
solution: TrollChat.sln

mono: # none
  #- 3.8.0
  - 3.10.0
  #- 3.12.0
  #- latest

dotnet: 2.0.0

global_env: ASPNETCORE_ENVIRONMENT=Staging
global_env: DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
global_env: DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  - nuget sources add -Name aspnetcore-dev.dotnet.myget.org_MY -Source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
  - nuget sources add -Name api.nuget.org_MY -Source https://api.nuget.org/v3/index.json
  - nuget restore
  - dotnet restore

script:
  - dotnet build TrollChat.sln
  - dotnet build ./TrollChat.DataAccess
  - dotnet build ./TrollChat.BusinessLogic
  - dotnet build ./TrollChat.BusinessLogic.Tests
  - dotnet test ./TrollChat.BusinessLogic.Tests
