dist: trusty
sudo: false

language: csharp
solution: TrollChat.sln

mono: none
  #- 3.8.0
  #- 3.10.0
  #- 3.12.0
  #- latest

dotnet: 1.1.0

global_env: ASPNETCORE_ENVIRONMENT=Staging
global_env: DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
global_env: DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  - dotnet restore

script:
  - dotnet build ./TrollChat.DataAccess -c Release
  - dotnet build ./TrollChat.BusinessLogic -c Release
  - dotnet build ./TrollChat.Web -c Release
  - dotnet build ./TrollChat.BusinessLogic.Tests -c Release
  - dotnet build TrollChat.sln -c Release
  - dotnet test ./TrollChat.BusinessLogic.Tests -c Release # --no-build
