dist: trusty
sudo: false

language: csharp
solution: TrollChat.sln

mono:
  #- 3.8.0
  - 3.10.0
  - 3.12.0
  #- latest

#dotnet: 1.1.0

global_env: ASPNETCORE_ENVIRONMENT=Staging

before_script:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.1.2
  - dotnet restore

script:
  - dotnet build ./TrollChat.DataAccess -c Release
  - dotnet build ./TrollChat.BusinessLogic -c Release
  - dotnet build ./TrollChat.Web -c Release
  - dotnet build ./TrollChat.BusinessLogic.Tests -c Release
  - dotnet build TrollChat.sln -c Release
  - dotnet test ./TrollChat.BusinessLogic.Tests -c Release # --no-build
