image: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_build:
  - cmd: nuget sources add -Name aspnetcore-dev.dotnet.myget.org -Source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
  - cmd: nuget restore
  - cmd: dotnet restore
