image: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_build:
  - cmd: nuget restore
  - cmd: dotnet restore
  - cmd: dotnet build -c Release
  - cmd: dotnet test ./TrollChat.BusinessLogic.Tests -c Release --no-build
