version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: >-
    dotnet --info

    nuget restore

    dotnet restore
build:
  verbosity: quiet
before_test:
- cmd: dotnet test ./TrollChat.BusinessLogic.Tests --no-build
test:
  assemblies:
    only:
    - ./TrollChat.BusinessLogic.Tests
