image: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_build:
  - cmd: dotnet --info
  - cmd: nuget restore
  - cmd: dotnet restore

#after_build:
  - cmd: dotnet test ./TrollChat.BusinessLogic.Tests #--no-build
