version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build:
  - cmd: nuget restore
  - cmd: dotnet --info
  - cmd: cd c:\users\appveyor\.nuget\packages
  - cmd: dir
  - cmd: 'cd %USERPROFILE%'
  - cmd: dir
  - cmd: cd .nuget
  - cmd: dir
  #- cmd: dotnet restore

build:
  verbosity: quiet

test_script:
  #- cmd: dotnet test ./TrollChat.BusinessLogic.Tests --no-build
  - cmd: '%USERPROFILE%/.nuget/packages/opencover/4.6.519/tools/OpenCover.Console.exe' -register:user #-target:"dotnet" -targetargs:"test TrollChat.BusinessLogic.Tests --no-build" -output:"coverage.xml"

after_test:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
